-- Create project_locations table
create table if not exists public.project_locations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.clients(id) on delete cascade not null,
  name text not null,
  unique(project_id, name)
);

-- Enable RLS
alter table public.project_locations enable row level security;

-- Policies
create policy "Enable read access for all users" on public.project_locations
  for select using (true);

create policy "Enable insert for all users" on public.project_locations
  for insert with check (true);

create policy "Enable update for all users" on public.project_locations
  for update using (true);

create policy "Enable delete for all users" on public.project_locations
  for delete using (true);
