-- Run this in Supabase SQL Editor to create the Blacklist table
create table public.blacklist (
  id bigint generated by default as identity primary key,
  phone text unique,
  instagram text,
  full_name text,
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (optional but recommended)
alter table public.blacklist enable row level security;

-- Allow public read access (so the bot/site can check it)
create policy "Allow public read access"
  on public.blacklist for select
  using ( true );

-- Allow service role (bot) full access
-- (Service role bypasses RLS by default, but good to be explicit if needed for authenticated users)
