-- 1. Create 'clients' table (Projects)
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  thread_id bigint unique not null
);

-- 2. Create 'team' table (Crew members)
create table if not exists public.team (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  telegram_id bigint unique not null,
  username text,
  full_name text,
  role text default 'crew'
);

-- 3. Enable Row Level Security (RLS)
alter table public.clients enable row level security;
alter table public.team enable row level security;

-- 4. Create Policies (Allow public READ access so frontend can fetch lists)
create policy "Enable read access for all users" on public.clients
  for select using (true);
  
create policy "Enable read access for all users" on public.team
  for select using (true);

-- 5. Create Policies (Allow insert/update for backend via Service Role - usually automatic, 
-- but we can add public insert if we want the bot to write freely without service key, 
-- though using Service Key in backend is safer. For now, let's allow public insert for simplicity in prototyping if needed, 
-- OR rely on the backend using the Service Key (which bypasses RLS). 
-- Since we are using the generic client in Python, let's explicitly allow insert for now to avoid permission issues 
-- until we configure the Service Key properly).
create policy "Enable insert for all users" on public.clients
  for insert with check (true);

create policy "Enable update for all users" on public.clients
  for update using (true);

create policy "Enable insert for all users" on public.team
  for insert with check (true);

create policy "Enable update for all users" on public.team
  for update using (true);
