import unittest
from unittest.mock import patch, MagicMock
import os
import sys

# Patch environment variables before importing
os.environ['SUPABASE_URL'] = 'https://mock.supabase.co'
os.environ['SUPABASE_KEY'] = 'mock_key'
os.environ['BOT_KEY'] = 'mock_bot_key'
os.environ['SUPABASE_PAT'] = 'mock_pat'

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from api.index import ensure_blacklist_table

class TestEnsureBlacklistTable(unittest.TestCase):

    def setUp(self):
        self.expected_sql = """
    create table if not exists public.blacklist (
      id bigint generated by default as identity primary key,
      phone text unique,
      instagram text,
      full_name text,
      reason text,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null
    );
    alter table public.blacklist enable row level security;
    create policy "Allow public read access" on public.blacklist for select using ( true );
    """
        self.expected_url = "https://api.supabase.com/v1/projects/waekzofajzqcpoeldhkt/query"
        self.expected_headers = {
            "Authorization": "Bearer mock_pat",
            "Content-Type": "application/json"
        }
        self.expected_payload = {"query": self.expected_sql}

    @patch('api.index.requests.post')
    def test_ensure_blacklist_table_success_200(self, mock_post):
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_post.return_value = mock_response

        result = ensure_blacklist_table()

        self.assertTrue(result)
        mock_post.assert_called_once_with(
            self.expected_url,
            json=self.expected_payload,
            headers=self.expected_headers
        )

    @patch('api.index.requests.post')
    def test_ensure_blacklist_table_success_201(self, mock_post):
        mock_response = MagicMock()
        mock_response.status_code = 201
        mock_post.return_value = mock_response

        result = ensure_blacklist_table()

        self.assertTrue(result)
        mock_post.assert_called_once_with(
            self.expected_url,
            json=self.expected_payload,
            headers=self.expected_headers
        )

    @patch('api.index.requests.post')
    def test_ensure_blacklist_table_failure_400(self, mock_post):
        mock_response = MagicMock()
        mock_response.status_code = 400
        mock_response.text = "Bad Request"
        mock_post.return_value = mock_response

        result = ensure_blacklist_table()

        self.assertFalse(result)
        mock_post.assert_called_once_with(
            self.expected_url,
            json=self.expected_payload,
            headers=self.expected_headers
        )

    @patch('api.index.requests.post')
    def test_ensure_blacklist_table_exception(self, mock_post):
        mock_post.side_effect = Exception("Network Error")

        result = ensure_blacklist_table()

        self.assertFalse(result)
        mock_post.assert_called_once_with(
            self.expected_url,
            json=self.expected_payload,
            headers=self.expected_headers
        )

if __name__ == '__main__':
    unittest.main()
